### ISSUE TITLE
tar: can't open '/tmp/menus.tar.gz': No such file or directory

### ISSUE THREAD

**Issue by rssfed23** [linuxserver/docker-netbootxyz#21]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Netboot xyz starts

## Current Behavior
For the last couple weeks, I've been unable to update netboot. I deployed from scratch on a completely clean environment, but running the initial startup script fails:
```
netbootxyz    | [cont-init.d] 10-adduser: exited 0.
netbootxyz    | [cont-init.d] 20-nginx-config: executing...
netbootxyz    | [cont-init.d] 20-nginx-config: exited 0.
netbootxyz    | [cont-init.d] 36-download-menus: executing...
netbootxyz    | [netbootxyz-init] Downloading Netboot.xyz at
netbootxyz    | tar: can't open '/tmp/menus.tar.gz': No such file or directory
netbootxyz    | cp: cannot stat '/config/menus/remote/*': No such file or directory
netbootxyz    | [cont-init.d] 36-download-menus: exited 0.
netbootxyz    | [cont-init.d] 99-custom-files: executing...
netbootxyz    | [custom-init] no custom files found exiting...
netbootxyz    | [cont-init.d] 99-custom-files: exited 0.
netbootxyz    | [cont-init.d] done.

```
This of course results in no images being present.

Also worthy to note, when trying to go to port 3000 to access the UI the following appears in the logs:
```
netbootxyz    | listening on *:3000
netbootxyz    | FxLNXiEvYTcB46oHAAAA connected time=1604927229656
netbootxyz    | undefined:1
netbootxyz    | undefined
netbootxyz    | ^
netbootxyz    |
netbootxyz    | SyntaxError: Unexpected token u in JSON at position 0
netbootxyz    |     at JSON.parse (<anonymous>)
netbootxyz    |     at Request._callback (/app/app.js:61:44)
netbootxyz    |     at self.callback (/app/node_modules/request/request.js:185:22)
netbootxyz    |     at Request.emit (events.js:315:20)
netbootxyz    |     at Request.onRequestError (/app/node_modules/request/request.js:877:8)
netbootxyz    |     at ClientRequest.emit (events.js:315:20)
netbootxyz    |     at TLSSocket.socketErrorListener (_http_client.js:426:9)
netbootxyz    |     at TLSSocket.emit (events.js:315:20)
netbootxyz    |     at emitErrorNT (internal/streams/destroy.js:92:8)
netbootxyz    |     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
```
## Environment
**OS:** Ubuntu 20.04
**CPU architecture:** x86_64/
**How docker service was installed:**
Official docker install script

## Command used to create docker container (run/create/compose/screenshot)
My compose file:
```---
version: "2.1"
services:
  netbootxyz:
    image: linuxserver/netbootxyz:latest
    container_name: netbootxyz
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./config:/config
      - ./assets:/assets #optional
    ports:
      - 3000:3000
      - 69:69/udp
      - 80:80 #optional
    restart: unless-stopped
    networks:
      tftp_network:
        ipv4_address: 10.0.0.13

networks:
  tftp_network:
    driver: macvlan
    driver_opts:
      parent: enx847beb4e2639
    ipam:
      config:
        - subnet: 10.0.0.0/24            # <-- Update
          gateway: 10.0.0.1              # <-- Update
          ip_range: 10.0.0.13/28        # <-- Update```

**Comment by rssfed23** [comment]
Closing this. The issue was my own stupid fault - I had changed the gateway address recently on the local LAN but not updated the macvlan network netboot was on *doh*
