### ISSUE TITLE
OpenWRT Dashboard Timeout with Undefined 1

### ISSUE THREAD

**Issue by aphorise** [linuxserver/docker-netbootxyz#41]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Work as per other platforms / OS tested where the same menu working fine but not in OpenWRT. It's also worth noting that other images from linuxserver work fine on the same host.

## Current Behavior
When visiting the default stats page an exception is encountered as ntoed below - yet other pages `menus` & `local assets` work fine.
![unknown](https://user-images.githubusercontent.com/974854/180870064-681acc6c-a6f5-4beb-81ef-5b2a9ab07655.png)

## Steps to Reproduce

1. On openwrt `docker run` the image as shown below.
2. Follow [install instruction](https://docs.linuxserver.io/images/docker-netbootxyz#application-setup) also with note to the following GH issue: #36 
3. Go to URL in browser with inspect view in Browser where a socket.io request just times out & `undefined:1` exception is encountered.

## Environment
**OS:** Linux OpenWrt 5.10.127
**CPU architecture:** x86_64
**How docker service was installed:**
```
docker run -d --name=netbootxyz -e PUID=1000 -e PGID=1000 -p 3000:3000 -p 69:69/udp -p 8080:80 --restart unless-stopped -v /root/netbootxyz:/config -v /mnt/nvme_shares/netbootxyz:/assets lscr.io/linuxserver/netbootxyz:latest
```

## Command used to create docker container (run/create/compose/screenshot)
```
docker run -d --name=netbootxyz -e PUID=1000 -e PGID=1000 -p 3000:3000 -p 69:69/udp -p 8080:80 --restart unless-stopped -v /root/netbootxyz:/config -v /mnt/nvme_shares/netbootxyz:/assets lscr.io/linuxserver/netbootxyz:latest
```

## Docker logs
```
uname -ar && docker --version
  # Linux OpenWrt 5.10.127 #0 SMP Wed Jul 6 19:09:39 2022 x86_64 GNU/Linux
  # Docker version 20.10.17, build 100c701

docker run -d --name=netbootxyz -e PUID=1000 -e PGID=1000 -p 3000:3000 -p 69:69/udp -p 8080:80 --restart unless-stopped -v /root/netbootxyz:/config -v /mnt/nvme_shares/netbootxyz:/assets lscr.io/linuxserver/netbootxyz:latest
  # stderr: s6-rc: info: service s6rc-oneshot-runner: starting
  # stderr: s6-rc: info: service s6rc-oneshot-runner successfully started
  # stderr: s6-rc: info: service fix-attrs: starting
  # stderr: s6-rc: info: service 00-legacy: starting
  # stderr: s6-rc: info: service 00-legacy successfully started
  # stderr: s6-rc: info: service fix-attrs successfully started
  # stderr: s6-rc: info: service legacy-cont-init: starting
  # stderr: cont-init: info: running /etc/cont-init.d/01-envfile
  # stderr: cont-init: info: /etc/cont-init.d/01-envfile exited 0
  # stderr: cont-init: info: running /etc/cont-init.d/02-tamper-check
  # stderr: cont-init: info: /etc/cont-init.d/02-tamper-check exited 0
  # stderr: cont-init: info: running /etc/cont-init.d/10-adduser
  # stdout: 
  # stdout: -------------------------------------
  # stdout:           _         ()
  # stdout:          | |  ___   _    __
  # stdout:          | | / __| | |  /  \
  # stdout:          | | \__ \ | | | () |
  # stdout:          |_| |___/ |_|  \__/
  # stdout: 
  # stdout: 
  # stdout: Brought to you by linuxserver.io
  # stdout: -------------------------------------
  # stdout: 
  # stdout: To support the app dev(s) visit:
  # stdout: netboot.xyz: https://opencollective.com/netbootxyz/donate
  # stdout: 
  # stdout: To support LSIO projects visit:
  # stdout: https://www.linuxserver.io/donate/
  # stdout: -------------------------------------
  # stdout: GID/UID
  # stdout: -------------------------------------
  # stdout: 
  # stdout: User uid:    1000
  # stdout: User gid:    1000
  # stdout: -------------------------------------
  # stdout: 
  # stderr: cont-init: info: /etc/cont-init.d/10-adduser exited 0
  # stderr: cont-init: info: running /etc/cont-init.d/20-nginx-config
  # stderr: cont-init: info: /etc/cont-init.d/20-nginx-config exited 0
  # stderr: cont-init: info: running /etc/cont-init.d/36-download-menus
  # stdout: [netbootxyz-init] Downloading Netboot.xyz at 
  # stderr: tar: can't open '/tmp/menus.tar.gz': No such file or directory
  # stderr: cp: cannot stat '/config/menus/remote/*': No such file or directory
  # stderr: cont-init: info: /etc/cont-init.d/36-download-menus exited 0
  # stderr: cont-init: info: running /etc/cont-init.d/90-custom-folders
  # stderr: cont-init: info: /etc/cont-init.d/90-custom-folders exited 0
  # stderr: cont-init: info: running /etc/cont-init.d/99-custom-files
  # stdout: [custom-init] no custom files found exiting...
  # stderr: cont-init: info: /etc/cont-init.d/99-custom-files exited 0
  # stderr: s6-rc: info: service legacy-cont-init successfully started
  # stderr: s6-rc: info: service legacy-services: starting
  # stderr: services-up: info: copying legacy longrun nginx (no readiness notification)
  # stderr: services-up: info: copying legacy longrun tftp (no readiness notification)
  # stderr: services-up: info: copying legacy longrun webapp (no readiness notification)
  # stderr: s6-rc: info: service legacy-services successfully started
  # stderr: s6-rc: info: service 99-ci-service-check: starting
  # stdout: [ls.io-init] done.
  # stderr: s6-rc: info: service 99-ci-service-check successfully started
  # stdout: listening on *:3000
  # stdout: cpdwg3Sz4Z5RPqoRAAAB connected time=1658602687923
  # stdout: j4zJX3jAt0Iv0VP1AAAD connected time=1658602688769
  # stdout: 9zVJGtYpzbro3LVMAAAF connected time=1658602695432
  # stderr: undefined:1
  # stderr: undefined
  # stderr: ^
  # stderr: 
  # stderr: SyntaxError: Unexpected token u in JSON at position 0
  # stderr:     at JSON.parse (<anonymous>)
  # stderr:     at Request._callback (/app/app.js:66:44)
  # stderr:     at self.callback (/app/node_modules/request/request.js:185:22)
  # stderr:     at Request.emit (events.js:400:28)
  # stderr:     at Request.onRequestError (/app/node_modules/request/request.js:877:8)
  # stderr:     at ClientRequest.emit (events.js:400:28)
  # stderr:     at TLSSocket.socketErrorListener (_http_client.js:475:9)
  # stderr:     at TLSSocket.emit (events.js:400:28)
  # stderr:     at emitErrorNT (internal/streams/destroy.js:106:8)
  # stderr:     at emitErrorCloseNT (internal/streams/destroy.js:74:3)
  # stdout: listening on *:3000
  # stdout: kYV64qFenT1B25kxAAAB connected time=1658602701704
  # stdout: xWkpWWa512Z5AIV_AAAD connected time=1658602701768
```

**Comment by j0nnymoe** [comment]
Your logs are showing permissions issues.

**Comment by aphorise** [comment]
Issue was Interface & Firewall related. I realised this by trying out `docker run ... --net=host` where everything worked as expected yet using dockers default `bridge` mode caused issues due to upstream limitation things would only partially work as described earlier.

In my case I'm running my **`dockerd`** using a custom lauch script and in OpenWRT Luci I added my `docker0` interface:
![image](https://user-images.githubusercontent.com/974854/181014488-c42114d0-26fb-4986-94c9-4771905bb8ac.png)

I then proceeded to add Firewall rules with `Masquerading`:
![image](https://user-images.githubusercontent.com/974854/181014851-9dab6a55-b7b9-4532-899b-e43faf62f468.png)
